[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
is-system = true
# Add --system-mode = true in the compiler for the same effect



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
